Implement Packit to openssh-keys
coreos/openssh-keys pull request #103
Opened 2024-05-08 19:16 UTC by yasminvalim

This PR is about using Packit to automate releases for [openssh-keys](https://github.com/coreos/openssh-keys). We tested it in coreos-installer and found it effective. Now, we're working in an epic to add it in all coreos packages repos. 

You can learn more about Packit in its documentation [here](https://packit.dev/docs).

2024-06-10 13:21 UTC, prestist approved these changes
LGTM. I hope the 'rust2rpm' is enough. I guess we will see.

2024-06-12 13:20 UTC, prestist requested changes
@HuijingHei ran into to rust2rpm not being on the packit service. 

she has created an issue on their board. look here: https://issues.redhat.com/browse/PACKIT-3719

So until that is resolved, we should not try this.

2024-07-08 19:03 UTC, prestist commented
Hmm, Can you squash the two commits into one?

2024-07-08 20:53 UTC, prestist commented
Overall lgtm. Just need the commits squashed.

2024-07-08 21:30 UTC, yasminvalim commented
> Overall lgtm. Just need the commits squashed.

I did a rebase with main and just let one commit here. 

I think its ready to be approved now.

2024-07-09 01:34 UTC, HuijingHei commented on .packit.yaml
> +    - fedora-all
Overall LGTM, is it necessary change this to `fedora-rawhide`, then backport to other branches?

2024-07-09 13:09 UTC, yasminvalim commented on .packit.yaml
> +    - fedora-all
I think it is. It should be `fedora-rawhide `just to ` propose_downstream `or to the other jobs too?

2024-07-09 13:32 UTC, HuijingHei commented on .packit.yaml
> +    - fedora-all
I think just to `propose_downstream` is enough. Trigger PR to rawhide branch and then can backport to other branch.

2024-07-10 16:31 UTC, prestist approved these changes

2024-07-10 16:31 UTC, merged